services:
  - type: web
    name: snyptr-backend
    runtime: python
    runtimeVersion: 3.9.18
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn server:app
    envVars:
      - key: FLASK_ENV
        value: production
